-- 📦 Produkty
INSERT INTO produkty (nazwa, opis, cena, ilosc, typ_ceny, zdjecie, id_kategorii) VALUES
('Bagietka', 'Świeża bagietka pszenna', 2.49, 100, 'szt', 'bagietka.jpg', 1),
('Banan', 'Dojrzałe banany z Ekwadoru', 5.99, 150, 'kg', 'banan.jpg', 2),
('Bułki', 'Miękkie bułeczki śniadaniowe', 3.00, 120, 'szt', 'bulki.jpg', 1),
('Cebula', 'Cebula biała', 2.90, 80, 'kg', 'cebula.jpg', 3),
('Chleb', 'Chleb żytni razowy', 4.20, 60, 'szt', 'chleb.jpg', 1),
('Cola', 'Napój gazowany Coca-Cola', 4.99, 100, 'szt', 'cola.jpg', 5),
('Czekolada', 'Czekolada mleczna Wedel', 3.50, 75, 'szt', 'czekolada.jpg', 5),
('Herbata', 'Herbata owocowa 20 torebek', 6.50, 50, 'szt', 'herbata.jpg', 5),
('Jabłka', 'Jabłka z polskich sadów', 4.50, 100, 'kg', 'jablka.jpg', 2),
('Jogurt', 'Jogurt naturalny 200g', 2.30, 60, 'szt', 'jogurt.jpg', 1),
('Karkówka', 'Mięso karkowe wieprzowe', 17.90, 30, 'kg', 'karkowka.jpg', 4),
('Kinder', 'Batonik Kinder', 2.99, 70, 'szt', 'kinder.jpg', 5),
('Kurczak', 'Pierś z kurczaka świeża', 16.99, 40, 'kg', 'kurczak.jpg', 4),
('Marchewka', 'Marchew ekologiczna', 3.20, 90, 'kg', 'marchewka.jpg', 3),
('Masło', 'Masło ekstra 200g', 6.70, 50, 'szt', 'maslo.jpg', 1),
('Mleko', 'Mleko 2% 1L', 3.99, 100, 'szt', 'mleko.jpg', 1),
('Ogórki', 'Ogórki gruntowe', 4.10, 70, 'kg', 'ogorki.jpg', 3),
('Oreo', 'Ciasteczka Oreo', 4.80, 90, 'szt', 'oreo.jpg', 5),
('Parówki', 'Parówki wieprzowe', 8.90, 60, 'kg', 'parowki.jpg', 4),
('Pomidory', 'Soczyste pomidory malinowe', 5.20, 110, 'kg', 'pomidory.jpg', 3),
('Rogaliki', 'Rogaliki z marmoladą', 3.30, 40, 'szt', 'rogalki.jpg', 1),
('Schab', 'Schab bez kości', 18.40, 35, 'kg', 'schab.jpg', 4),
('Ser', 'Ser żółty gouda', 24.50, 45, 'kg', 'ser.jpg', 1),
('Sok', 'Sok pomarańczowy 1L', 5.50, 85, 'szt', 'sok.jpg', 5),
('Twaróg', 'Twaróg półtłusty', 4.20, 50, 'szt', 'twarog.jpg', 1),
('Woda', 'Woda mineralna 1.5L', 2.00, 100, 'szt', 'woda.jpg', 5),
('Żelki', 'Żelki owocowe Haribo', 4.70, 80, 'szt', 'zelki.jpg', 5),
('Ziemniaki', 'Ziemniaki młode', 2.20, 120, 'kg', 'ziemniaki.jpg', 3);
